In [1]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [46]:
a = np.array([i for i in range(12, 24, 1)])
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [59]:
a.resize(3, 4)
a
a.resize(2, 6)
a
a.resize(6, 2)
a
a.reshape(4, 3)
a.reshape(1, 12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

####  3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [41]:
np.reshape(a, (4, -1))
np.reshape(a, (3, -1))
np.reshape(a, (2, -1))
np.reshape(a, (-1, 2))
np.reshape(a, (-1, 3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
нет

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [74]:
a = np.random.randn(3, 4)
print(a)
b = a.flatten()
print (b)
np.size(a) == np.size(b)

[[-0.25155847 -0.89298016 -0.389644    1.85816964]
 [-0.22611857  0.44276507 -0.90294743 -2.82434221]
 [ 0.03893849 -0.52483799  2.01336368  1.80029834]]
[-0.25155847 -0.89298016 -0.389644    1.85816964 -0.22611857  0.44276507
 -0.90294743 -2.82434221  0.03893849 -0.52483799  2.01336368  1.80029834]


True

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0  невключительно с интервалом 2.

In [76]:
a = np.array([i for i in range(20, 0, -2)])

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

Не знаю, в чем тут подвох :) Может быть я не понимаю сути вопроса, но массивы ничем не будут отличаться, как их не называй.

In [77]:
b = np.array([i for i in range(20, 0, -2)])

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [93]:
a = np.zeros((3, 2))
print(a)
b = np.ones((2, 2))
print(b)
ab = np.concatenate((a, b), axis=0)
print(f'size: {np.size(ab)}')

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
size: 10


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [126]:
a = np.array([i for i in range(0, 12, 1)])
print(f'a:\n{a}\n')
A = a.reshape(4, 3)
print(f'A:\n{A}\n')
At = A.T
print(f'At:\n{At}\n')
B = np.matmul(A, At)
print(f'B:\n{B}\n')
#np.linalg.inv(B) - ошибка LinAlgError, так как если определитель матрицы равен нулю, то обратной матрицы нет
print(f'Определитель матрицы B: {np.linalg.det(B)}\n')

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

A:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

At:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

Определитель матрицы B: 0.0



#### 10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [129]:
np.random.seed(42)

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [131]:
c = np.random.randint(0, 16, 16)

array([ 3,  7,  7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [161]:
C = c.reshape(4, 4)
print(C)
D = B + (C*10)
D_inv = np.linalg.inv(D)
D_inv

[[ 3  7  7  2]
 [ 5  4  1  7]
 [11 13  5  1]
 [15 11  4  0]]


array([[-0.02745824, -0.02127921, -0.00030506,  0.01848067],
       [-0.00983038, -0.00115445,  0.03006537, -0.01967443],
       [ 0.03091391,  0.00259603, -0.0266755 ,  0.01263576],
       [-0.00169622,  0.01154454, -0.00065371, -0.00325571]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [163]:
D_inv = np.where (D_inv < 0, 0, 1)
D_inv

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0]])

In [164]:
E = np.where (D_inv, B, C)
E

array([[  3,   7,   7,  32],
       [  5,   4,  86,   7],
       [ 23,  86,   5, 212],
       [ 15, 122,   4,   0]])